### ISSUE TITLE
[THANKS] Gradle and updated dependecies

### ISSUE THREAD

**Issue by vrudikov** [kgusarov/spring-boot-netty#1]
Hi, @kgusarov!
I really liked this project
It's so convenient to use it with Spring Boot. I would like to see it as a Spring Boot team project :)

I did some things:
- updated deps
- added Gradle as a build tool
- refactored test to be in touch with updated Spring Boot

You can look at [my master](https://github.com/vrudikov/spring-boot-netty)

Thanks for you work!

**Comment by kgusarov** [comment]
Hi, @vrudikov!

Thanks for the feedback. I am glad that my toy project was useful to someone. Unfortunately I won't have enough time till mid of July to do the proper support of it :) But I took a look at the changes you've made - seems fine to me. Also I have some questions to you:
* Do you think `@PreHandler` should be renamed to something like `@Handler`? I was always frustrated by the term I came up with - in project I've used this code they were always *pre*
* How easy was it to understand API and stuff?

Thanks in advance!
Konstantin

**Comment by vrudikov** [comment]
> Do you think @PreHandler should be renamed to something like @Handler? I was always frustrated by the term I came up with - in project I've used this code they were always pre

So my main question - what's the role of those `@PreHandler` classes? In the Netty arch we have a pipeline where we define chain of handlers.

```
ChannelPipeline pipeline = ch.pipeline();
pipeline.addLast(sslContext().newHandler(ch.alloc()));
pipeline.addLast(new LoggingHandler(LogLevel.INFO));
pipeline.addLast("decoder", new CustomProtobufDecoder());
pipeline.addLast("encoder", new CustomProtobufEncoder());
pipeline.addLast("encoder", new LogginRequestHandler());
```

What are examples of _pre_ logic?

> How easy was it to understand API and stuff?

API is super easy to understand. And it's neat and very clean. That's why I liked it much and grabbed to my project 👍

**Comment by kgusarov** [comment]
`@PreHandlers` work like filters in Servlets, so that's why I am not totally happy with naming. In your example these would be pre-handlers:
```
pipeline.addLast(sslContext().newHandler(ch.alloc()));
pipeline.addLast(new LoggingHandler(LogLevel.INFO));
pipeline.addLast("decoder", new CustomProtobufDecoder());
pipeline.addLast("encoder", new CustomProtobufEncoder());
```

Since they do not handle logic itself, but instead prepare everything before and after actual handling.

**Comment by vrudikov** [comment]
Oh! I got it. So chose a cleaner approach - you have pre-processors mapped by `@PreHandler`, and `@On` works only for Message processing.

Need to think about it... Netty has that feature when you can build pipeline on the fly - you can add pre-handlers and remove them. But anyway - 90% of the time you work with static pipeline

**Comment by kgusarov** [comment]
Yes, this is something that is not currently covered. It could be possible for example to rename this to `@Filter` and make it possible to use also factories instead of fixed instances...
